-- ============================================================
-- WYP Assist: North American Venue Seed Data
-- Major Stadiums, Arenas, and Theatres
-- All venues set to status = 'approved'
-- ============================================================

-- ══════════════════════════════════════════════════════════════
-- NFL STADIUMS
-- ══════════════════════════════════════════════════════════════
INSERT INTO public.venues (name, city, state, country, venue_type, capacity, status) VALUES
('SoFi Stadium', 'Inglewood', 'CA', 'US', 'stadium', 70240, 'approved'),
('Allegiant Stadium', 'Las Vegas', 'NV', 'US', 'stadium', 65000, 'approved'),
('AT&T Stadium', 'Arlington', 'TX', 'US', 'stadium', 80000, 'approved'),
('MetLife Stadium', 'East Rutherford', 'NJ', 'US', 'stadium', 82500, 'approved'),
('Caesars Superdome', 'New Orleans', 'LA', 'US', 'stadium', 73208, 'approved'),
('State Farm Stadium', 'Glendale', 'AZ', 'US', 'stadium', 63400, 'approved'),
('Lumen Field', 'Seattle', 'WA', 'US', 'stadium', 68740, 'approved'),
('Arrowhead Stadium', 'Kansas City', 'MO', 'US', 'stadium', 76416, 'approved'),
('Empower Field at Mile High', 'Denver', 'CO', 'US', 'stadium', 76125, 'approved'),
('Hard Rock Stadium', 'Miami Gardens', 'FL', 'US', 'stadium', 64767, 'approved'),
('Gillette Stadium', 'Foxborough', 'MA', 'US', 'stadium', 65878, 'approved'),
('Lincoln Financial Field', 'Philadelphia', 'PA', 'US', 'stadium', 69796, 'approved'),
('M&T Bank Stadium', 'Baltimore', 'MD', 'US', 'stadium', 71008, 'approved'),
('Nissan Stadium', 'Nashville', 'TN', 'US', 'stadium', 69143, 'approved'),
('Bank of America Stadium', 'Charlotte', 'NC', 'US', 'stadium', 74867, 'approved'),
('Mercedes-Benz Stadium', 'Atlanta', 'GA', 'US', 'stadium', 71000, 'approved'),
('Raymond James Stadium', 'Tampa', 'FL', 'US', 'stadium', 65890, 'approved'),
('Lambeau Field', 'Green Bay', 'WI', 'US', 'stadium', 81441, 'approved'),
('Soldier Field', 'Chicago', 'IL', 'US', 'stadium', 61500, 'approved'),
('Ford Field', 'Detroit', 'MI', 'US', 'stadium', 65000, 'approved'),
('U.S. Bank Stadium', 'Minneapolis', 'MN', 'US', 'stadium', 66860, 'approved'),
('Lucas Oil Stadium', 'Indianapolis', 'IN', 'US', 'stadium', 67000, 'approved'),
('GEHA Field at Arrowhead', 'Kansas City', 'MO', 'US', 'stadium', 76416, 'approved'),
('Highmark Stadium', 'Orchard Park', 'NY', 'US', 'stadium', 71608, 'approved'),
('Paycor Stadium', 'Cincinnati', 'OH', 'US', 'stadium', 65515, 'approved'),
('FirstEnergy Stadium', 'Cleveland', 'OH', 'US', 'stadium', 67895, 'approved'),
('Acrisure Stadium', 'Pittsburgh', 'PA', 'US', 'stadium', 68400, 'approved'),
('TIAA Bank Field', 'Jacksonville', 'FL', 'US', 'stadium', 67838, 'approved'),
('NRG Stadium', 'Houston', 'TX', 'US', 'stadium', 72220, 'approved'),
('Levi''s Stadium', 'Santa Clara', 'CA', 'US', 'stadium', 68500, 'approved'),
('FedExField', 'Landover', 'MD', 'US', 'stadium', 82000, 'approved'),
('Commanders Field', 'Landover', 'MD', 'US', 'stadium', 82000, 'approved');

-- ══════════════════════════════════════════════════════════════
-- MLB STADIUMS
-- ══════════════════════════════════════════════════════════════
INSERT INTO public.venues (name, city, state, country, venue_type, capacity, status) VALUES
('Dodger Stadium', 'Los Angeles', 'CA', 'US', 'stadium', 56000, 'approved'),
('Yankee Stadium', 'Bronx', 'NY', 'US', 'stadium', 46537, 'approved'),
('Fenway Park', 'Boston', 'MA', 'US', 'stadium', 37755, 'approved'),
('Wrigley Field', 'Chicago', 'IL', 'US', 'stadium', 41649, 'approved'),
('Oracle Park', 'San Francisco', 'CA', 'US', 'stadium', 41915, 'approved'),
('Citi Field', 'Queens', 'NY', 'US', 'stadium', 41922, 'approved'),
('Petco Park', 'San Diego', 'CA', 'US', 'stadium', 40209, 'approved'),
('T-Mobile Park', 'Seattle', 'WA', 'US', 'stadium', 47929, 'approved'),
('Truist Park', 'Atlanta', 'GA', 'US', 'stadium', 41084, 'approved'),
('Globe Life Field', 'Arlington', 'TX', 'US', 'stadium', 40300, 'approved'),
('Minute Maid Park', 'Houston', 'TX', 'US', 'stadium', 41168, 'approved'),
('Busch Stadium', 'St. Louis', 'MO', 'US', 'stadium', 45494, 'approved'),
('PNC Park', 'Pittsburgh', 'PA', 'US', 'stadium', 38362, 'approved'),
('Great American Ball Park', 'Cincinnati', 'OH', 'US', 'stadium', 42319, 'approved'),
('Chase Field', 'Phoenix', 'AZ', 'US', 'stadium', 48519, 'approved'),
('Coors Field', 'Denver', 'CO', 'US', 'stadium', 50144, 'approved'),
('Target Field', 'Minneapolis', 'MN', 'US', 'stadium', 38544, 'approved'),
('Nationals Park', 'Washington', 'DC', 'US', 'stadium', 41339, 'approved'),
('Camden Yards', 'Baltimore', 'MD', 'US', 'stadium', 45971, 'approved'),
('Kauffman Stadium', 'Kansas City', 'MO', 'US', 'stadium', 37903, 'approved'),
('Rogers Centre', 'Toronto', 'ON', 'CA', 'stadium', 49282, 'approved'),
('Tropicana Field', 'St. Petersburg', 'FL', 'US', 'stadium', 25025, 'approved'),
('American Family Field', 'Milwaukee', 'WI', 'US', 'stadium', 41900, 'approved'),
('Guaranteed Rate Field', 'Chicago', 'IL', 'US', 'stadium', 40615, 'approved'),
('Progressive Field', 'Cleveland', 'OH', 'US', 'stadium', 34830, 'approved'),
('Comerica Park', 'Detroit', 'MI', 'US', 'stadium', 41083, 'approved'),
('Citizens Bank Park', 'Philadelphia', 'PA', 'US', 'stadium', 42792, 'approved'),
('Angel Stadium', 'Anaheim', 'CA', 'US', 'stadium', 45517, 'approved'),
('Oakland Coliseum', 'Oakland', 'CA', 'US', 'stadium', 46847, 'approved'),
('LoanDepot Park', 'Miami', 'FL', 'US', 'stadium', 36742, 'approved');

-- ══════════════════════════════════════════════════════════════
-- NBA/NHL ARENAS
-- ══════════════════════════════════════════════════════════════
INSERT INTO public.venues (name, city, state, country, venue_type, capacity, status) VALUES
('Madison Square Garden', 'New York', 'NY', 'US', 'arena', 20789, 'approved'),
('Crypto.com Arena', 'Los Angeles', 'CA', 'US', 'arena', 20000, 'approved'),
('Chase Center', 'San Francisco', 'CA', 'US', 'arena', 18064, 'approved'),
('United Center', 'Chicago', 'IL', 'US', 'arena', 20917, 'approved'),
('TD Garden', 'Boston', 'MA', 'US', 'arena', 19156, 'approved'),
('Little Caesars Arena', 'Detroit', 'MI', 'US', 'arena', 20332, 'approved'),
('Ball Arena', 'Denver', 'CO', 'US', 'arena', 19520, 'approved'),
('Scotiabank Arena', 'Toronto', 'ON', 'CA', 'arena', 19800, 'approved'),
('American Airlines Center', 'Dallas', 'TX', 'US', 'arena', 19200, 'approved'),
('Toyota Center', 'Houston', 'TX', 'US', 'arena', 18055, 'approved'),
('Barclays Center', 'Brooklyn', 'NY', 'US', 'arena', 17732, 'approved'),
('Capital One Arena', 'Washington', 'DC', 'US', 'arena', 20356, 'approved'),
('Fiserv Forum', 'Milwaukee', 'WI', 'US', 'arena', 17341, 'approved'),
('State Farm Arena', 'Atlanta', 'GA', 'US', 'arena', 18118, 'approved'),
('Wells Fargo Center', 'Philadelphia', 'PA', 'US', 'arena', 20478, 'approved'),
('Kaseya Center', 'Miami', 'FL', 'US', 'arena', 19600, 'approved'),
('Amalie Arena', 'Tampa', 'FL', 'US', 'arena', 19092, 'approved'),
('Smoothie King Center', 'New Orleans', 'LA', 'US', 'arena', 16867, 'approved'),
('Target Center', 'Minneapolis', 'MN', 'US', 'arena', 18978, 'approved'),
('Gainbridge Fieldhouse', 'Indianapolis', 'IN', 'US', 'arena', 18165, 'approved'),
('Paycom Center', 'Oklahoma City', 'OK', 'US', 'arena', 18203, 'approved'),
('Moda Center', 'Portland', 'OR', 'US', 'arena', 19441, 'approved'),
('Vivint Arena', 'Salt Lake City', 'UT', 'US', 'arena', 18306, 'approved'),
('Footprint Center', 'Phoenix', 'AZ', 'US', 'arena', 18055, 'approved'),
('Golden 1 Center', 'Sacramento', 'CA', 'US', 'arena', 17608, 'approved'),
('Spectrum Center', 'Charlotte', 'NC', 'US', 'arena', 19077, 'approved'),
('FedExForum', 'Memphis', 'TN', 'US', 'arena', 18119, 'approved'),
('Frost Bank Center', 'San Antonio', 'TX', 'US', 'arena', 18581, 'approved'),
('Rocket Mortgage FieldHouse', 'Cleveland', 'OH', 'US', 'arena', 19432, 'approved'),
('PPG Paints Arena', 'Pittsburgh', 'PA', 'US', 'arena', 18387, 'approved'),
('Prudential Center', 'Newark', 'NJ', 'US', 'arena', 16514, 'approved'),
('UBS Arena', 'Elmont', 'NY', 'US', 'arena', 17255, 'approved'),
('Bell Centre', 'Montreal', 'QC', 'CA', 'arena', 21302, 'approved'),
('Canadian Tire Centre', 'Ottawa', 'ON', 'CA', 'arena', 18652, 'approved'),
('Rogers Arena', 'Vancouver', 'BC', 'CA', 'arena', 18910, 'approved'),
('Rogers Place', 'Edmonton', 'AB', 'CA', 'arena', 18347, 'approved'),
('Scotiabank Saddledome', 'Calgary', 'AB', 'CA', 'arena', 19289, 'approved'),
('Canada Life Centre', 'Winnipeg', 'MB', 'CA', 'arena', 15321, 'approved'),
('SAP Center', 'San Jose', 'CA', 'US', 'arena', 17435, 'approved'),
('Honda Center', 'Anaheim', 'CA', 'US', 'arena', 17174, 'approved'),
('Climate Pledge Arena', 'Seattle', 'WA', 'US', 'arena', 17100, 'approved'),
('T-Mobile Arena', 'Las Vegas', 'NV', 'US', 'arena', 17500, 'approved'),
('Enterprise Center', 'St. Louis', 'MO', 'US', 'arena', 18096, 'approved'),
('Bridgestone Arena', 'Nashville', 'TN', 'US', 'arena', 17159, 'approved'),
('PNC Arena', 'Raleigh', 'NC', 'US', 'arena', 18680, 'approved'),
('Amerant Bank Arena', 'Sunrise', 'FL', 'US', 'arena', 19250, 'approved'),
('Nationwide Arena', 'Columbus', 'OH', 'US', 'arena', 18144, 'approved'),
('KeyBank Center', 'Buffalo', 'NY', 'US', 'arena', 19070, 'approved'),
('Xcel Energy Center', 'St. Paul', 'MN', 'US', 'arena', 17954, 'approved'),
('Intuit Dome', 'Inglewood', 'CA', 'US', 'arena', 18000, 'approved');

-- ══════════════════════════════════════════════════════════════
-- MAJOR THEATRES & PERFORMING ARTS CENTERS
-- ══════════════════════════════════════════════════════════════
INSERT INTO public.venues (name, city, state, country, venue_type, capacity, status) VALUES
-- New York
('Radio City Music Hall', 'New York', 'NY', 'US', 'theatre', 5960, 'approved'),
('Beacon Theatre', 'New York', 'NY', 'US', 'theatre', 2894, 'approved'),
('David Geffen Hall', 'New York', 'NY', 'US', 'theatre', 2738, 'approved'),
('Metropolitan Opera House', 'New York', 'NY', 'US', 'theatre', 3800, 'approved'),
('Carnegie Hall', 'New York', 'NY', 'US', 'theatre', 2804, 'approved'),
('Apollo Theater', 'New York', 'NY', 'US', 'theatre', 1506, 'approved'),
('Kings Theatre', 'Brooklyn', 'NY', 'US', 'theatre', 3200, 'approved'),
('Hammerstein Ballroom', 'New York', 'NY', 'US', 'theatre', 2200, 'approved'),
('Terminal 5', 'New York', 'NY', 'US', 'theatre', 3000, 'approved'),
('Brooklyn Academy of Music', 'Brooklyn', 'NY', 'US', 'theatre', 2109, 'approved'),
('The Town Hall', 'New York', 'NY', 'US', 'theatre', 1500, 'approved'),
-- Los Angeles / SoCal
('Hollywood Bowl', 'Los Angeles', 'CA', 'US', 'amphitheatre', 17500, 'approved'),
('Greek Theatre', 'Los Angeles', 'CA', 'US', 'amphitheatre', 5870, 'approved'),
('The Wiltern', 'Los Angeles', 'CA', 'US', 'theatre', 1850, 'approved'),
('Dolby Theatre', 'Hollywood', 'CA', 'US', 'theatre', 3332, 'approved'),
('The Forum', 'Inglewood', 'CA', 'US', 'arena', 17505, 'approved'),
('YouTube Theater', 'Inglewood', 'CA', 'US', 'theatre', 6000, 'approved'),
('Walt Disney Concert Hall', 'Los Angeles', 'CA', 'US', 'theatre', 2265, 'approved'),
('The Novo', 'Los Angeles', 'CA', 'US', 'theatre', 2300, 'approved'),
('Shrine Auditorium', 'Los Angeles', 'CA', 'US', 'theatre', 6300, 'approved'),
('The Pantages Theatre', 'Hollywood', 'CA', 'US', 'theatre', 2703, 'approved'),
-- Chicago
('Chicago Theatre', 'Chicago', 'IL', 'US', 'theatre', 3600, 'approved'),
('Auditorium Theatre', 'Chicago', 'IL', 'US', 'theatre', 3875, 'approved'),
('Riviera Theatre', 'Chicago', 'IL', 'US', 'theatre', 2500, 'approved'),
('Cadillac Palace Theatre', 'Chicago', 'IL', 'US', 'theatre', 2346, 'approved'),
('Lyric Opera House', 'Chicago', 'IL', 'US', 'theatre', 3563, 'approved'),
-- Nashville
('Ryman Auditorium', 'Nashville', 'TN', 'US', 'theatre', 2362, 'approved'),
('Grand Ole Opry House', 'Nashville', 'TN', 'US', 'theatre', 4400, 'approved'),
('TPAC Andrew Jackson Hall', 'Nashville', 'TN', 'US', 'theatre', 2472, 'approved'),
-- Las Vegas
('The Colosseum at Caesars', 'Las Vegas', 'NV', 'US', 'theatre', 4298, 'approved'),
('Dolby Live at Park MGM', 'Las Vegas', 'NV', 'US', 'theatre', 5200, 'approved'),
('The Venetian Theatre', 'Las Vegas', 'NV', 'US', 'theatre', 1815, 'approved'),
('Resorts World Theatre', 'Las Vegas', 'NV', 'US', 'theatre', 5000, 'approved'),
('MGM Grand Garden Arena', 'Las Vegas', 'NV', 'US', 'arena', 17157, 'approved'),
('Michelob Ultra Arena', 'Las Vegas', 'NV', 'US', 'arena', 12000, 'approved'),
('The Pearl at Palms', 'Las Vegas', 'NV', 'US', 'theatre', 2500, 'approved'),
-- San Francisco / Bay Area
('The Masonic', 'San Francisco', 'CA', 'US', 'theatre', 3300, 'approved'),
('The Warfield', 'San Francisco', 'CA', 'US', 'theatre', 2300, 'approved'),
('Bill Graham Civic Auditorium', 'San Francisco', 'CA', 'US', 'theatre', 7000, 'approved'),
('Fox Theater', 'Oakland', 'CA', 'US', 'theatre', 2800, 'approved'),
('Shoreline Amphitheatre', 'Mountain View', 'CA', 'US', 'amphitheatre', 22500, 'approved'),
-- Philadelphia
('The Met Philadelphia', 'Philadelphia', 'PA', 'US', 'theatre', 3500, 'approved'),
('Academy of Music', 'Philadelphia', 'PA', 'US', 'theatre', 2509, 'approved'),
('Tower Theater', 'Upper Darby', 'PA', 'US', 'theatre', 3048, 'approved'),
('Mann Center', 'Philadelphia', 'PA', 'US', 'amphitheatre', 14000, 'approved'),
-- Boston
('Boch Center Wang Theatre', 'Boston', 'MA', 'US', 'theatre', 3500, 'approved'),
('Boch Center Shubert Theatre', 'Boston', 'MA', 'US', 'theatre', 1500, 'approved'),
('Orpheum Theatre', 'Boston', 'MA', 'US', 'theatre', 2700, 'approved'),
-- Washington DC
('The Anthem', 'Washington', 'DC', 'US', 'theatre', 6000, 'approved'),
('Kennedy Center Concert Hall', 'Washington', 'DC', 'US', 'theatre', 2442, 'approved'),
('Kennedy Center Opera House', 'Washington', 'DC', 'US', 'theatre', 2364, 'approved'),
('DAR Constitution Hall', 'Washington', 'DC', 'US', 'theatre', 3702, 'approved'),
('Warner Theatre', 'Washington', 'DC', 'US', 'theatre', 1847, 'approved'),
-- Atlanta
('Fox Theatre', 'Atlanta', 'GA', 'US', 'theatre', 4665, 'approved'),
('Tabernacle', 'Atlanta', 'GA', 'US', 'theatre', 2600, 'approved'),
('Coca-Cola Roxy', 'Atlanta', 'GA', 'US', 'theatre', 3600, 'approved'),
-- Dallas / Houston / Texas
('AT&T Performing Arts Center', 'Dallas', 'TX', 'US', 'theatre', 2060, 'approved'),
('Majestic Theatre', 'Dallas', 'TX', 'US', 'theatre', 1700, 'approved'),
('Hobby Center for the Performing Arts', 'Houston', 'TX', 'US', 'theatre', 2650, 'approved'),
('Bass Concert Hall', 'Austin', 'TX', 'US', 'theatre', 2900, 'approved'),
('Moody Theater (ACL Live)', 'Austin', 'TX', 'US', 'theatre', 2750, 'approved'),
('Majestic Theatre', 'San Antonio', 'TX', 'US', 'theatre', 2311, 'approved'),
-- Denver
('Red Rocks Amphitheatre', 'Morrison', 'CO', 'US', 'amphitheatre', 9525, 'approved'),
('Bellco Theatre', 'Denver', 'CO', 'US', 'theatre', 5000, 'approved'),
('Paramount Theatre', 'Denver', 'CO', 'US', 'theatre', 1870, 'approved'),
-- Seattle / Pacific NW
('Paramount Theatre', 'Seattle', 'WA', 'US', 'theatre', 2807, 'approved'),
('Moore Theatre', 'Seattle', 'WA', 'US', 'theatre', 1800, 'approved'),
('The Gorge Amphitheatre', 'George', 'WA', 'US', 'amphitheatre', 27500, 'approved'),
('Arlene Schnitzer Concert Hall', 'Portland', 'OR', 'US', 'theatre', 2776, 'approved'),
-- Miami / Florida
('Adrienne Arsht Center', 'Miami', 'FL', 'US', 'theatre', 2400, 'approved'),
('The Fillmore Miami Beach', 'Miami Beach', 'FL', 'US', 'theatre', 2700, 'approved'),
('Dr. Phillips Center', 'Orlando', 'FL', 'US', 'theatre', 2700, 'approved'),
('Straz Center', 'Tampa', 'FL', 'US', 'theatre', 2610, 'approved'),
-- Detroit / Michigan
('Fox Theatre', 'Detroit', 'MI', 'US', 'theatre', 5048, 'approved'),
('Masonic Temple Theatre', 'Detroit', 'MI', 'US', 'theatre', 4404, 'approved'),
('Fisher Theatre', 'Detroit', 'MI', 'US', 'theatre', 2089, 'approved'),
-- Minneapolis
('Orpheum Theatre', 'Minneapolis', 'MN', 'US', 'theatre', 2579, 'approved'),
('State Theatre', 'Minneapolis', 'MN', 'US', 'theatre', 2181, 'approved'),
-- Other Major Markets
('The Fabulous Fox Theatre', 'St. Louis', 'MO', 'US', 'theatre', 4192, 'approved'),
('Taft Theatre', 'Cincinnati', 'OH', 'US', 'theatre', 2500, 'approved'),
('Palace Theatre', 'Columbus', 'OH', 'US', 'theatre', 2691, 'approved'),
('Benedum Center', 'Pittsburgh', 'PA', 'US', 'theatre', 2800, 'approved'),
('Shea''s Performing Arts Center', 'Buffalo', 'NY', 'US', 'theatre', 3019, 'approved'),
('DPAC', 'Durham', 'NC', 'US', 'theatre', 2712, 'approved'),
('Ovens Auditorium', 'Charlotte', 'NC', 'US', 'theatre', 2400, 'approved'),
('Saenger Theatre', 'New Orleans', 'LA', 'US', 'theatre', 2600, 'approved'),
('Peabody Opera House', 'St. Louis', 'MO', 'US', 'theatre', 3100, 'approved'),
('Orpheum Theatre', 'Memphis', 'TN', 'US', 'theatre', 2300, 'approved'),
('Brown Theatre', 'Louisville', 'KY', 'US', 'theatre', 2971, 'approved'),
('The Louisville Palace', 'Louisville', 'KY', 'US', 'theatre', 2700, 'approved'),
-- Canada
('Massey Hall', 'Toronto', 'ON', 'CA', 'theatre', 2765, 'approved'),
('Roy Thomson Hall', 'Toronto', 'ON', 'CA', 'theatre', 2630, 'approved'),
('Princess of Wales Theatre', 'Toronto', 'ON', 'CA', 'theatre', 2000, 'approved'),
('Ed Mirvish Theatre', 'Toronto', 'ON', 'CA', 'theatre', 2300, 'approved'),
('Four Seasons Centre', 'Toronto', 'ON', 'CA', 'theatre', 2071, 'approved'),
('Place des Arts', 'Montreal', 'QC', 'CA', 'theatre', 2982, 'approved'),
('National Arts Centre', 'Ottawa', 'ON', 'CA', 'theatre', 2323, 'approved'),
('Queen Elizabeth Theatre', 'Vancouver', 'BC', 'CA', 'theatre', 2929, 'approved'),
('Orpheum Theatre', 'Vancouver', 'BC', 'CA', 'theatre', 2672, 'approved'),
('Jubilee Auditorium', 'Edmonton', 'AB', 'CA', 'theatre', 2538, 'approved'),
('Jubilee Auditorium', 'Calgary', 'AB', 'CA', 'theatre', 2538, 'approved'),
-- Mexico
('Foro Sol', 'Mexico City', '', 'MX', 'stadium', 65000, 'approved'),
('Auditorio Nacional', 'Mexico City', '', 'MX', 'theatre', 10000, 'approved'),
('Palacio de los Deportes', 'Mexico City', '', 'MX', 'arena', 22370, 'approved'),
('Arena Monterrey', 'Monterrey', '', 'MX', 'arena', 17500, 'approved');

-- ══════════════════════════════════════════════════════════════
-- AMPHITHEATRES
-- ══════════════════════════════════════════════════════════════
INSERT INTO public.venues (name, city, state, country, venue_type, capacity, status) VALUES
('Budweiser Stage', 'Toronto', 'ON', 'CA', 'amphitheatre', 16000, 'approved'),
('Xfinity Center', 'Mansfield', 'MA', 'US', 'amphitheatre', 19900, 'approved'),
('Jones Beach Theater', 'Wantagh', 'NY', 'US', 'amphitheatre', 15200, 'approved'),
('PNC Bank Arts Center', 'Holmdel', 'NJ', 'US', 'amphitheatre', 17500, 'approved'),
('Merriweather Post Pavilion', 'Columbia', 'MD', 'US', 'amphitheatre', 19319, 'approved'),
('Jiffy Lube Live', 'Bristow', 'VA', 'US', 'amphitheatre', 25262, 'approved'),
('PNC Music Pavilion', 'Charlotte', 'NC', 'US', 'amphitheatre', 19500, 'approved'),
('Ameris Bank Amphitheatre', 'Alpharetta', 'GA', 'US', 'amphitheatre', 12000, 'approved'),
('MIDFLORIDA Credit Union Amphitheatre', 'Tampa', 'FL', 'US', 'amphitheatre', 20000, 'approved'),
('iTHINK Financial Amphitheatre', 'West Palm Beach', 'FL', 'US', 'amphitheatre', 19500, 'approved'),
('Hollywood Casino Amphitheatre', 'Maryland Heights', 'MO', 'US', 'amphitheatre', 20000, 'approved'),
('Pine Knob Music Theatre', 'Clarkston', 'MI', 'US', 'amphitheatre', 15274, 'approved'),
('Blossom Music Center', 'Cuyahoga Falls', 'OH', 'US', 'amphitheatre', 19000, 'approved'),
('Riverbend Music Center', 'Cincinnati', 'OH', 'US', 'amphitheatre', 20500, 'approved'),
('Dos Equis Pavilion', 'Dallas', 'TX', 'US', 'amphitheatre', 20000, 'approved'),
('Cynthia Woods Mitchell Pavilion', 'The Woodlands', 'TX', 'US', 'amphitheatre', 16500, 'approved'),
('FivePoint Amphitheatre', 'Irvine', 'CA', 'US', 'amphitheatre', 12000, 'approved'),
('North Island Credit Union Amphitheatre', 'Chula Vista', 'CA', 'US', 'amphitheatre', 20500, 'approved'),
('White River Amphitheatre', 'Auburn', 'WA', 'US', 'amphitheatre', 20000, 'approved'),
('Ruoff Music Center', 'Noblesville', 'IN', 'US', 'amphitheatre', 24000, 'approved'),
('Sunlight Supply Amphitheater', 'Ridgefield', 'WA', 'US', 'amphitheatre', 17750, 'approved'),
('Alpine Valley Music Theatre', 'East Troy', 'WI', 'US', 'amphitheatre', 37000, 'approved'),
('Bethel Woods Center for the Arts', 'Bethel', 'NY', 'US', 'amphitheatre', 15000, 'approved'),
('Saratoga Performing Arts Center', 'Saratoga Springs', 'NY', 'US', 'amphitheatre', 25000, 'approved'),
('Coastal Credit Union Music Park', 'Raleigh', 'NC', 'US', 'amphitheatre', 20000, 'approved');

-- ══════════════════════════════════════════════════════════════
-- CONVENTION CENTERS (Major ones used for concerts/events)
-- ══════════════════════════════════════════════════════════════
INSERT INTO public.venues (name, city, state, country, venue_type, capacity, status) VALUES
('Javits Center', 'New York', 'NY', 'US', 'convention_center', 40000, 'approved'),
('McCormick Place', 'Chicago', 'IL', 'US', 'convention_center', 60000, 'approved'),
('Las Vegas Convention Center', 'Las Vegas', 'NV', 'US', 'convention_center', 50000, 'approved'),
('Orange County Convention Center', 'Orlando', 'FL', 'US', 'convention_center', 45000, 'approved'),
('George R. Brown Convention Center', 'Houston', 'TX', 'US', 'convention_center', 30000, 'approved'),
('Kay Bailey Hutchison Convention Center', 'Dallas', 'TX', 'US', 'convention_center', 35000, 'approved'),
('Georgia World Congress Center', 'Atlanta', 'GA', 'US', 'convention_center', 40000, 'approved'),
('Colorado Convention Center', 'Denver', 'CO', 'US', 'convention_center', 25000, 'approved'),
('Ernest N. Morial Convention Center', 'New Orleans', 'LA', 'US', 'convention_center', 35000, 'approved'),
('Boston Convention and Exhibition Center', 'Boston', 'MA', 'US', 'convention_center', 20000, 'approved'),
('Walter E. Washington Convention Center', 'Washington', 'DC', 'US', 'convention_center', 30000, 'approved'),
('Metro Toronto Convention Centre', 'Toronto', 'ON', 'CA', 'convention_center', 25000, 'approved'),
('Palais des congres de Montreal', 'Montreal', 'QC', 'CA', 'convention_center', 20000, 'approved'),
('Vancouver Convention Centre', 'Vancouver', 'BC', 'CA', 'convention_center', 18000, 'approved');
