import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

const RECIPIENTS = [
  "MRich@christielites.com",
  "tbaxt@christielites.com",
  "costa@wypproductions.com",
  "evan@rodecap.co",
];

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const {
      from_name,
      from_email,
      project_name,
      venue,
      show_date,
      return_date,
      country,
      d8_status,
      total_hoists,
      chain_system,
      pdf_base64,
    } = req.body;

    if (!from_name || !from_email || !project_name) {
      return res.status(400).json({ error: "Missing required fields" });
    }

    const { data, error } = await resend.emails.send({
      from: "WYP Assist <noreply@wypassist.com>",
      to: RECIPIENTS,
      subject: `Quote Request: ${project_name} — ${from_name}`,
      html: `
        <div style="font-family:Arial,sans-serif;max-width:640px;margin:0 auto">
          <div style="background:#ED0000;padding:16px 24px;border-radius:8px 8px 0 0">
            <h1 style="color:#fff;margin:0;font-size:20px;letter-spacing:1px">WYP ASSIST — Quote Request</h1>
          </div>
          <div style="background:#1A1A1A;padding:24px;color:#F5F5F5;border-radius:0 0 8px 8px">
            <table style="width:100%;border-collapse:collapse;font-size:14px">
              <tr><td style="padding:8px 12px;color:#9A9A9A;width:140px">Requested By</td><td style="padding:8px 12px;font-weight:bold">${from_name}</td></tr>
              <tr><td style="padding:8px 12px;color:#9A9A9A">Email</td><td style="padding:8px 12px"><a href="mailto:${from_email}" style="color:#FF2B2B">${from_email}</a></td></tr>
              <tr><td style="padding:8px 12px;color:#9A9A9A">Project</td><td style="padding:8px 12px;font-weight:bold">${project_name}</td></tr>
              <tr><td style="padding:8px 12px;color:#9A9A9A">Venue</td><td style="padding:8px 12px">${venue || "—"}</td></tr>
              <tr><td style="padding:8px 12px;color:#9A9A9A">Show Date</td><td style="padding:8px 12px">${show_date}</td></tr>
              <tr><td style="padding:8px 12px;color:#9A9A9A">Return Date</td><td style="padding:8px 12px">${return_date || "N/A"}</td></tr>
              <tr><td style="padding:8px 12px;color:#9A9A9A">Country / Region</td><td style="padding:8px 12px">${country}</td></tr>
              <tr><td style="padding:8px 12px;color:#9A9A9A">Chain System</td><td style="padding:8px 12px">${chain_system}</td></tr>
              <tr><td style="padding:8px 12px;color:#9A9A9A">Total Hoists</td><td style="padding:8px 12px;font-weight:bold;font-size:16px">${total_hoists}</td></tr>
              ${d8_status !== "Standard" ? `<tr><td style="padding:8px 12px;color:#E74C3C;font-weight:bold" colspan="2">⚠ ${d8_status}</td></tr>` : ""}
            </table>
            <div style="margin-top:20px;padding-top:16px;border-top:1px solid #3A3A3A;font-size:11px;color:#666">
              Generated by WYP Assist v1.1.0 — Pull sheet PDF attached
            </div>
          </div>
        </div>
      `,
      attachments: pdf_base64
        ? [
            {
              filename: `WYP_PullSheet_${project_name.replace(/\s+/g, "_")}.pdf`,
              content: pdf_base64,
              type: "application/pdf",
            },
          ]
        : [],
    });

    if (error) {
      console.error("Resend error:", error);
      return res.status(500).json({ error: error.message });
    }

    return res.status(200).json({ success: true, id: data.id });
  } catch (err) {
    console.error("Server error:", err);
    return res.status(500).json({ error: "Failed to send email" });
  }
}
